const GK_QUESTIONS=[
{q:"What is the capital of Australia?",o:["Sydney","Melbourne","Canberra","Brisbane"],a:2},
{q:"Which is the longest river in the world?",o:["Amazon","Nile","Yangtze","Mississippi"],a:1},
{q:"Mount Everest is in which mountain range?",o:["Andes","Alps","Himalayas","Rockies"],a:2},
{q:"What is the smallest country in the world?",o:["Monaco","Vatican City","San Marino","Liechtenstein"],a:1},
{q:"Which country has the most natural lakes?",o:["Russia","USA","Canada","Finland"],a:2},
{q:"The Sahara Desert is on which continent?",o:["Asia","South America","Africa","Australia"],a:2},
{q:"Which ocean is the largest?",o:["Atlantic","Indian","Arctic","Pacific"],a:3},
{q:"What is the capital of Brazil?",o:["Rio de Janeiro","São Paulo","Brasília","Salvador"],a:2},
{q:"What is the chemical symbol for gold?",o:["Go","Gd","Au","Ag"],a:2},
{q:"How many bones are in the adult human body?",o:["196","206","216","226"],a:1},
{q:"What planet is the Red Planet?",o:["Jupiter","Venus","Saturn","Mars"],a:3},
{q:"What gas do plants absorb from the atmosphere?",o:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],a:2},
{q:"What is the atomic number of hydrogen?",o:["2","0","3","1"],a:3},
{q:"What is H2O commonly known as?",o:["Hydrogen Peroxide","Salt Water","Water","Vinegar"],a:2},
{q:"DNA stands for?",o:["Deoxyribonucleic Acid","Dinitrogen Acid","Dipeptide Nucleic Acid","None"],a:0},
{q:"What is the powerhouse of the cell?",o:["Nucleus","Ribosome","Mitochondria","Golgi Apparatus"],a:2},
{q:"Which element has the symbol Fe?",o:["Fluorine","Iron","Francium","Fermium"],a:1},
{q:"What is the hardest natural substance on Earth?",o:["Gold","Quartz","Diamond","Titanium"],a:2},
{q:"Who proposed the theory of relativity?",o:["Newton","Bohr","Einstein","Hawking"],a:2},
{q:"Most abundant gas in Earth's atmosphere?",o:["Oxygen","Carbon Dioxide","Argon","Nitrogen"],a:3},
{q:"In which year did World War II end?",o:["1943","1944","1945","1946"],a:2},
{q:"Who was the first US President?",o:["Abraham Lincoln","George Washington","Thomas Jefferson","John Adams"],a:1},
{q:"The French Revolution began in which year?",o:["1789","1776","1799","1815"],a:0},
{q:"Which ancient wonder still exists?",o:["Colossus of Rhodes","Great Pyramid of Giza","Lighthouse of Alexandria","Hanging Gardens"],a:1},
{q:"Who discovered America in 1492?",o:["Vasco da Gama","Ferdinand Magellan","Christopher Columbus","Amerigo Vespucci"],a:2},
{q:"The Berlin Wall fell in which year?",o:["1987","1988","1989","1990"],a:2},
{q:"First man on the Moon?",o:["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","John Glenn"],a:2},
{q:"Magna Carta was signed in which year?",o:["1215","1315","1415","1115"],a:0},
{q:"Napoleon was exiled to which island?",o:["Corsica","Elba","Saint Helena","Malta"],a:2},
{q:"WWI started in which year?",o:["1912","1913","1914","1915"],a:2},
{q:"What is the value of Pi (2 decimal places)?",o:["3.12","3.14","3.16","3.18"],a:1},
{q:"Square root of 144?",o:["11","12","13","14"],a:1},
{q:"What is 15% of 200?",o:["25","30","35","40"],a:1},
{q:"Next prime number after 7?",o:["8","9","10","11"],a:3},
{q:"2 to the power of 10?",o:["512","1024","2048","256"],a:1},
{q:"Sum of angles in a triangle?",o:["90°","180°","270°","360°"],a:1},
{q:"Who wrote Romeo and Juliet?",o:["Charles Dickens","William Shakespeare","Jane Austen","Mark Twain"],a:1},
{q:"Who wrote 1984?",o:["Aldous Huxley","Ray Bradbury","George Orwell","H.G. Wells"],a:2},
{q:"Harry Potter was created by?",o:["Roald Dahl","J.R.R. Tolkien","C.S. Lewis","J.K. Rowling"],a:3},
{q:"The Great Gatsby was written by?",o:["Ernest Hemingway","F. Scott Fitzgerald","John Steinbeck","William Faulkner"],a:1},
{q:"Who wrote Pride and Prejudice?",o:["Charlotte Brontë","Emily Brontë","Jane Austen","Virginia Woolf"],a:2},
{q:"Iliad and Odyssey attributed to?",o:["Virgil","Homer","Socrates","Plato"],a:1},
{q:"Who co-founded Apple with Steve Jobs?",o:["Bill Gates","Steve Wozniak","Paul Allen","Larry Page"],a:1},
{q:"HTTP stands for?",o:["HyperText Transfer Protocol","High Transfer Text Process","Hyper Text Transmission Port","None"],a:0},
{q:"Who invented the World Wide Web?",o:["Bill Gates","Tim Berners-Lee","Vint Cerf","Steve Jobs"],a:1},
{q:"CPU stands for?",o:["Central Processing Unit","Computer Power Unit","Core Processing Utility","Central Power Unit"],a:0},
{q:"Who founded Microsoft?",o:["Steve Jobs","Larry Ellison","Bill Gates and Paul Allen","Mark Zuckerberg"],a:2},
{q:"HTML is used for?",o:["Styling web pages","Structuring web content","Server logic","Database queries"],a:1},
{q:"GPS stands for?",o:["Global Positioning System","General Precision Satellite","Ground Positioning Standard","Global Precision Signal"],a:0},
{q:"How many players on a football (soccer) team?",o:["9","10","11","12"],a:2},
{q:"Olympics originated in which country?",o:["Rome","Egypt","Greece","China"],a:2},
{q:"How many Grand Slam tennis tournaments?",o:["2","3","4","5"],a:2},
{q:"FIFA World Cup held every how many years?",o:["2","3","4","5"],a:2},
{q:"Which sport uses a puck?",o:["Polo","Cricket","Ice Hockey","Lacrosse"],a:2},
{q:"How many rings on the Olympic flag?",o:["4","5","6","7"],a:1},
{q:"Country with most FIFA World Cups?",o:["Germany","Argentina","Italy","Brazil"],a:3},
{q:"How many continents are there?",o:["5","6","7","8"],a:2},
{q:"Currency of Japan?",o:["Yuan","Won","Yen","Ringgit"],a:2},
{q:"Largest organ in the human body?",o:["Liver","Brain","Lungs","Skin"],a:3},
{q:"Planet closest to the Sun?",o:["Venus","Earth","Mercury","Mars"],a:2},
{q:"Most spoken language in the world?",o:["English","Spanish","Mandarin Chinese","Hindi"],a:2},
{q:"Days in a leap year?",o:["364","365","366","367"],a:2},
{q:"Largest mammal in the world?",o:["Elephant","Blue Whale","Giraffe","Hippo"],a:1},
{q:"Eiffel Tower is in which city?",o:["London","Rome","Berlin","Paris"],a:3},
{q:"How many primary colors?",o:["2","3","4","5"],a:1},
{q:"Country with the largest land area?",o:["China","USA","Russia","Canada"],a:2},
{q:"Capital of Canada?",o:["Toronto","Vancouver","Montreal","Ottawa"],a:3},
{q:"Colosseum is in which city?",o:["Athens","Rome","Venice","Florence"],a:1},
{q:"Smallest continent?",o:["Europe","Antarctica","Australia","South America"],a:2},
{q:"Capital of Argentina?",o:["Lima","Bogotá","Buenos Aires","Santiago"],a:2},
{q:"Capital of Japan?",o:["Osaka","Kyoto","Tokyo","Hiroshima"],a:2},
{q:"Capital of India?",o:["Mumbai","Kolkata","New Delhi","Bangalore"],a:2},
{q:"Capital of Egypt?",o:["Alexandria","Luxor","Cairo","Aswan"],a:2},
{q:"Capital of Russia?",o:["St. Petersburg","Vladivostok","Moscow","Kazan"],a:2},
{q:"Capital of Mexico?",o:["Guadalajara","Mexico City","Monterrey","Puebla"],a:1},
{q:"Capital of China?",o:["Shanghai","Guangzhou","Hong Kong","Beijing"],a:3},
{q:"Capital of Pakistan?",o:["Karachi","Lahore","Islamabad","Peshawar"],a:2},
{q:"Capital of Turkey?",o:["Istanbul","Izmir","Ankara","Bursa"],a:2},
{q:"Gravity force discovered by?",o:["Newton","Bohr","Einstein","Hawking"],a:0},
{q:"Chemical symbol for silver?",o:["Si","Sv","Ag","Sr"],a:2},
{q:"Chemical formula for salt?",o:["NaCl","KCl","CaCl2","MgCl2"],a:0},
{q:"UN founded in which year?",o:["1943","1944","1945","1946"],a:2},
{q:"How many colors in a rainbow?",o:["5","6","7","8"],a:2},
{q:"Gas that makes soda fizzy?",o:["Oxygen","Nitrogen","Carbon Dioxide","Helium"],a:2},
{q:"Human body chromosome pairs?",o:["20","23","26","28"],a:1},
{q:"Who wrote The Art of War?",o:["Confucius","Lao Tzu","Sun Tzu","Mencius"],a:2},
{q:"USB stands for?",o:["Universal Serial Bus","Universal System Bandwidth","Unified Serial Base","Universal Standard Bus"],a:0},
{q:"Stonehenge is in which country?",o:["France","Ireland","Scotland","England"],a:3},
{q:"Which metal is liquid at room temperature?",o:["Lead","Mercury","Gallium","Sodium"],a:1},
{q:"OPEC stands for?",o:["Oil and Petroleum Exporting Countries","Organization of Petroleum Exporting Countries","Organization of Pacific Economic Countries","None"],a:1},
{q:"Yoga originated in which country?",o:["Tibet","China","India","Nepal"],a:2},
{q:"Adult human teeth count?",o:["28","30","32","34"],a:2},
{q:"Which country invented paper?",o:["Egypt","India","Japan","China"],a:3},
{q:"Deepest ocean trench?",o:["Tonga Trench","Puerto Rico Trench","Mariana Trench","Philippine Trench"],a:2},
{q:"Who invented the telephone?",o:["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Guglielmo Marconi"],a:2},
{q:"Who painted the Mona Lisa?",o:["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"],a:2},
{q:"Who composed Fur Elise?",o:["Mozart","Bach","Beethoven","Chopin"],a:2},
{q:"Who sculpted the statue of David?",o:["Leonardo da Vinci","Raphael","Donatello","Michelangelo"],a:3},
{q:"The Louvre is in which city?",o:["London","Rome","Madrid","Paris"],a:3},
{q:"Which country is the largest coffee producer?",o:["Colombia","Ethiopia","Vietnam","Brazil"],a:3},
{q:"Sushi originates from?",o:["China","Korea","Japan","Thailand"],a:2},
{q:"Pizza originates from?",o:["Greece","Spain","France","Italy"],a:3},
{q:"Light from the Sun takes how long to reach Earth?",o:["4 minutes","8 minutes","12 minutes","15 minutes"],a:1},
{q:"How many planets in our solar system?",o:["7","8","9","10"],a:1},
{q:"Our galaxy is called?",o:["Andromeda","Whirlpool","Milky Way","Triangulum"],a:2},
{q:"First artificial satellite?",o:["Explorer 1","Vostok","Sputnik","Apollo"],a:2},
{q:"Pluto is classified as?",o:["Planet","Moon","Dwarf Planet","Asteroid"],a:2},
{q:"Currency of Germany?",o:["Mark","Franc","Euro","Pound"],a:2},
{q:"Universal blood donor type?",o:["A+","B+","AB+","O-"],a:3},
{q:"Strings on a standard guitar?",o:["4","5","6","7"],a:2},
{q:"Rarest blood type?",o:["AB+","A-","AB-","B-"],a:2},
{q:"Vitamin for blood clotting?",o:["Vitamin A","Vitamin C","Vitamin D","Vitamin K"],a:3},
{q:"Who invented the light bulb?",o:["Nikola Tesla","Alexander Graham Bell","Thomas Edison","Benjamin Franklin"],a:2},
{q:"Statue of Liberty was a gift from?",o:["England","Spain","France","Germany"],a:2},
{q:"Smallest bone in the human body?",o:["Stapes","Femur","Radius","Tibia"],a:0},
{q:"Which organ produces insulin?",o:["Liver","Kidney","Pancreas","Stomach"],a:2},
{q:"Fastest land animal?",o:["Lion","Leopard","Cheetah","Greyhound"],a:2},
{q:"How many legs does a spider have?",o:["6","8","10","12"],a:1},
{q:"A group of lions is called?",o:["Pack","Herd","Pride","Flock"],a:2},
{q:"What do pandas primarily eat?",o:["Fish","Bamboo","Berries","Leaves"],a:1},
{q:"How many sides does a hexagon have?",o:["5","6","7","8"],a:1},
{q:"Speed of light approx in km/s?",o:["200,000","300,000","400,000","500,000"],a:1},
{q:"Boiling point of water in Celsius?",o:["90°C","95°C","100°C","105°C"],a:2},
{q:"Vitamin produced by sunlight?",o:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"],a:3},
{q:"Center of an atom?",o:["Electron","Proton","Nucleus","Neutron"],a:2},
{q:"Sound travels fastest through?",o:["Air","Water","Vacuum","Steel"],a:3},
{q:"What type of rock is marble?",o:["Igneous","Sedimentary","Metamorphic","Volcanic"],a:2},
{q:"Renaissance began in which country?",o:["France","Germany","Spain","Italy"],a:3},
{q:"First atomic bomb dropped on?",o:["Nagasaki","Tokyo","Osaka","Hiroshima"],a:3},
{q:"The Titanic sank in which year?",o:["1910","1911","1912","1913"],a:2},
{q:"First female Nobel Prize winner?",o:["Florence Nightingale","Marie Curie","Rosalind Franklin","Lise Meitner"],a:1},
{q:"Great Wall built mainly against?",o:["Mongols","Japanese","Koreans","Russians"],a:0},
{q:"Industrial Revolution began in which century?",o:["17th","18th","19th","20th"],a:1},
{q:"First female UK Prime Minister?",o:["Theresa May","Margaret Thatcher","Barbara Castle","Shirley Williams"],a:1},
{q:"Which civilization built Machu Picchu?",o:["Aztec","Mayan","Inca","Olmec"],a:2},
{q:"Cold War was between USA and?",o:["China","Soviet Union","Germany","Cuba"],a:1},
{q:"Last Pharaoh of ancient Egypt?",o:["Nefertiti","Cleopatra","Hatshepsut","Nefertari"],a:1},
{q:"Julius Caesar ruled which empire?",o:["Greek","Roman","Ottoman","Byzantine"],a:1},
{q:"Human eye can distinguish how many colors?",o:["1 million","10 million","100 million","1 billion"],a:1},
{q:"Perimeter formula of a circle?",o:["πr²","2πr","πd²","4πr"],a:1},
{q:"Area formula of a circle?",o:["πr²","2πr","πd²","4πr"],a:0},
{q:"Fibonacci sequence start?",o:["1,2,3,5","0,1,1,2","1,1,2,4","2,3,5,8"],a:1},
{q:"Elephant pregnancy length approx?",o:["12 months","15 months","18 months","22 months"],a:3},
{q:"A group of fish is called?",o:["Flock","Pack","School","Colony"],a:2},
{q:"Don Quixote written by?",o:["Pablo Neruda","Gabriel García Márquez","Miguel de Cervantes","Federico García Lorca"],a:2},
{q:"Which blood type is universal donor?",o:["A+","B+","O-","AB-"],a:2},
{q:"How many hours in a week?",o:["148","158","168","178"],a:2},
{q:"The Great Barrier Reef is near?",o:["New Zealand","Papua New Guinea","Australia","Indonesia"],a:2},
{q:"Which country has most pyramids?",o:["Egypt","Mexico","Sudan","Peru"],a:2},
{q:"Greenland belongs to which country?",o:["Norway","Iceland","USA","Denmark"],a:3},
{q:"Capital of South Africa?",o:["Johannesburg","Cape Town","Pretoria","Durban"],a:2},
{q:"Capital of Nigeria?",o:["Lagos","Kano","Abuja","Ibadan"],a:2},
{q:"Capital of South Korea?",o:["Busan","Seoul","Incheon","Daegu"],a:1},
{q:"What does AI stand for?",o:["Automated Intelligence","Artificial Intelligence","Advanced Integration","Algorithmic Input"],a:1},
{q:"Who invented the airplane?",o:["Thomas Edison","Alexander Bell","Wright Brothers","Nikola Tesla"],a:2},
{q:"What is the national sport of Canada?",o:["Ice Hockey and Lacrosse","Basketball","Baseball","Football"],a:0},
{q:"Mount Kilimanjaro is in which country?",o:["Kenya","Tanzania","Uganda","Ethiopia"],a:1},
{q:"Amazon River is primarily in?",o:["Colombia","Peru","Brazil","Venezuela"],a:2},
{q:"How many chambers in the human heart?",o:["2","3","4","5"],a:2},
{q:"Which planet has rings famously?",o:["Jupiter","Uranus","Neptune","Saturn"],a:3},
{q:"Process by which plants make food?",o:["Respiration","Photosynthesis","Fermentation","Digestion"],a:1},
{q:"Largest planet in our solar system?",o:["Saturn","Jupiter","Neptune","Uranus"],a:1},
{q:"Nile flows through how many countries?",o:["7","9","11","13"],a:2},
{q:"Tallest mountain in Africa?",o:["Mount Kenya","Mount Kilimanjaro","Ras Dashen","Mount Meru"],a:1},
{q:"Which country has the most natural lakes?",o:["Russia","USA","Canada","Finland"],a:2},
{q:"National currency of Germany?",o:["Mark","Franc","Euro","Pound"],a:2},
{q:"Who wrote Hamlet?",o:["Marlowe","Shakespeare","Dickens","Milton"],a:1},
{q:"What does RAM stand for?",o:["Random Access Memory","Read All Memory","Runtime Access Module","Rapid Access Mode"],a:0},
{q:"Which planet has the most moons?",o:["Jupiter","Saturn","Uranus","Neptune"],a:1},
{q:"What is the largest desert in the world?",o:["Sahara","Arabian","Gobi","Antarctic"],a:3},
{q:"Which gas makes up most of the Sun?",o:["Oxygen","Helium","Hydrogen","Nitrogen"],a:2},
{q:"What does URL stand for?",o:["Uniform Resource Locator","Universal Reference Link","Unified Record Listing","Upload Resource Label"],a:0},
{q:"What is the capital of Greece?",o:["Thessaloniki","Sparta","Corinth","Athens"],a:3},
{q:"Who invented the printing press?",o:["Leonardo da Vinci","Johannes Gutenberg","Galileo Galilei","Isaac Newton"],a:1},
{q:"What is the currency of the UK?",o:["Euro","Dollar","Pound Sterling","Franc"],a:2},
{q:"Lake Baikal is in which country?",o:["Mongolia","China","Kazakhstan","Russia"],a:3},
{q:"What is the capital of Saudi Arabia?",o:["Jeddah","Mecca","Medina","Riyadh"],a:3},
{q:"The Great Sphinx is in which country?",o:["Iraq","Jordan","Egypt","Libya"],a:2},
{q:"What is the capital of UAE?",o:["Dubai","Sharjah","Abu Dhabi","Ajman"],a:2},
{q:"How many zeros in one million?",o:["4","5","6","7"],a:2},
{q:"What is the square root of 256?",o:["14","15","16","17"],a:2},
{q:"Who was the first person in space?",o:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"],a:2},
{q:"What is the chemical symbol for oxygen?",o:["Ox","O2","O","Og"],a:2},
{q:"What is the capital of France?",o:["Lyon","Marseille","Paris","Bordeaux"],a:2},
{q:"What percentage of the Earth is covered by water?",o:["51%","61%","71%","81%"],a:2},
];
